branches:
  only:
  - main
language: python
cache: yarn
python:
  - '3.5'
before_install:
  - nvm install 10.16.3
install:
  - pip install fandogh-cli --upgrade
script:
  - echo $TRAVIS_COMMIT
  - COLLECT_ERROR=True fandogh login --username=$FANDOGH_USERNAME --password=$FANDOGH_PASSWORD
  - fandogh namespace active --name default
  - node --version
  - yarn
  - yarn build
  - fandogh source run
notifications:
  slack:
    rooms:
      - secure: "CmipsGiduy49Jvom5q2N6v5Mrxd7xbWry10fpuDmliQqBtj/axJwYAGO2+MxKjEu3Rl3beGs1sm/9NHHQxImWLYI6ZSMSf7sS2DdF4ZsIS+1yrjTA0ruqWOPfLrBcGFHz9U0UasatXd6JdBEc0ZwFv78lt044XibeTZqT68Pl7hDZktAu8dJRd9RwJK8378dabZNaJhlIs4wPuOWqC8gJH6rw86EqCmVJSNZYyGXtCw2xxvi0hgP5zsPVMpBjM46Q/KgpVfDeanyh51IzcKa5f5mtp8jzPXdMRBfUMwdM5hGpQ+y7AxzZZJ/Hch76+nMluLAG2LoSMSJ+JAN/gHWo/cJw8rzRwWZbILpj7wh0gZRX01Eyd46BSJ02wr37ojgmLq/+S6c05kch5osPf7P/6au79FcvJ4B+aXpVKLb7SFlABZ4DmI22i5VH2fBN6I0WH+4AD08LR0hNoRpw1ZFYo2qkPqOq/Oe5aHUm+NxauN0vVldrD2/qplXEKPxIBQrMUiBSEW7ziy5wo3+Mq+1bFk/j0a9Hn3dF26RK0gUYdp2HE0/Pc/42JM3V2SuK0KNAh9M5kHCvXwtBMsBeQrxAzkyvjAUE6UnWJ/scZ3hPrt9Inhwhvag1dgx5czfq8y7lz2+HzUT52dT/PvYTESFgJFAhygTLCfOInn2Kv7WxJs="
    on_success: always
    on_failure: always
