branches:
  only:
  - main
language: python
node_js: "10.16.3"
cache: yarn
python:
  - "3.5" 
# command to install dependencies
before_install:
  - sudo apt-get update
install:
  - pip install fandogh-cli --upgrade
# command to run tests
script:
  - echo $TRAVIS_COMMIT  
  - COLLECT_ERROR=True fandogh login --username=$FANDOGH_USERNAME --password=$FANDOGH_PASSWORD
  - fandogh namespace active --name default
  - node --version
  - yarn
  - yarn build
  - fandogh source run
