branches:
  only:
  - main
language: python
cache: yarn
python:
  - '3.5'
before_install:
  - nvm install 10.16.3
install:
  - pip install fandogh-cli --upgrade
script:
  - echo $TRAVIS_COMMIT
  - COLLECT_ERROR=True fandogh login --username=$FANDOGH_USERNAME --password=$FANDOGH_PASSWORD
  - fandogh namespace active --name default
  - node --version
  - yarn
  - yarn build
  - fandogh source run
notifications:
  slack:
    secure: H66aO9MXppFGTqv1rF/amUhAANj8ipEferd9r4Omph64sWIv4OywQ5Ar0M7OoezR13Pr08hsZJJgsHdMIDPKZgdtiu/e3J7T3j5nqELxg3XzJtFWx49owJuF+nHRnLUDqRg19TPlmQO+eQzS+E7MbYRyteJ77OuoU9hSvrUprpCsMX4kc3Xl8w4usy3jOg8yzxtgenHCA0sHAw5GdGXLT0S/xBLExnRxuWOLRRBkyzAEeZagd2d7Dv7+HgDHIK1CN2NlWJlJib5roCff9kCs+FSAGmM7w5VH4AjNnWR9uknOzUY8KrsfGKwdQR9BgDRPbV6Z2J3frv8UrfCxv+bpVkmKnJuqdxrm9lAt0Ifp5P1Yd5dSkw7G31JqVopck8Z0pLydudrDLH+WHs0I5e8hHeH/jeMSLVaxZeXl1qUl5wx8ZCuWsWZCRzqtpqHvQbICgUIrFQt7n20nXZDyJ/scIie03OcspLuwyJauDKVQ5SXAGTbgC1VHKAzT0X7Vbh7epgCN4aUjKMZGWSAegPlAHLWoluZMBxOgoFpeuMkFhkpVz5M4ottZEpArz78dhcv/r7SR+ckJXoEYYlcILZvZCZejOmKMFJABsyLXE31HgxlNT3lBpzQRH7MdTNN4azcLxQSKJVzGaEplOh+sOp/MaPR0zZDwolA07hEJgz1mEIE=
