branches:
  only:
  - main
language: python
cache: yarn
python:
  - '3.9'
before_install:
  - nvm install 10.16.3
install:
  - pip install fandogh-cli --upgrade
script:
  - echo $TRAVIS_COMMIT
  - COLLECT_ERROR=True fandogh login --username=$FANDOGH_USERNAME --password=$FANDOGH_PASSWORD
  - fandogh namespace active --name default
  - yarn
  - yarn build
  - fandogh source run
notifications:
  slack:
    rooms:
      - secure: "f6iV6TS7zwwXbVnYsUUEtpP/fqc0g+rrLzVhKebhrbMJAV9YDZ9ZAzE0Apo5G8str6/VYlt0lquHNqCsw+4U4UjwZ94F9hmWOeR/CQP5/9/CjCIY2dhCy8gGdhNCqb/jUhcIAn3CpxO7/HUsVGKAYsmipQ4/9Q3DJp0KwcWGnLLJfM7QbhhGzI6XpOXtRW0zCODQSreqpCdZpPyhBHTUTTu5TGfrGpSKLiHtbzGDBIervmHuqHiwccX12yQGiUerhMyG4MUyu7rujsSV6/xZIWGoL7N6TIYFJegV6MmK56LMdEL6er4aIi0tq9P1RcmgMnTKEY+09I+hnhItWFpgQKlH+1t7/cZl+zyG8UgMPXYrZrPVR/AONlgaDiQp8BqWEYiQ3zA3J/91wpgPVwsxIs95JQE+JVyxWQUERDfioCJy5WvLR+g3OHxiIfHNEWW6tBRwu09+c1aKgBwHwaVMks6cvKUKCdeMRSliKSRjWK3jNYWr5qlq3iIu7q+Mq7zJVKjfx7LE8ymau4RZMFCBNS2DMtpEqrRAeLQ9KKAwThiIY8jtwy9WiW2GfmIo5yRkoJSY1a8IuvIA6FSTPZqBbL5ekt3YPqD13nNxcq2aIQFvqA2VV8KBNNeOLvMrjJ9d6RKunTv2b6NEhTNRlZjYmWTWwyMHb8PPHobUDPu5C1A="
    on_success: always
    on_failure: always
